// 设置常量mutations

export const types = {
  // com
  COM_ITEM_TAB: 'COM_ITEM_TAB',
  COM_INIT_INDEX: 'COM_INIT_INDEX',
  COM_NAV_STATUS: 'COM_NAV_STATUS',
  COM_HEADER_STATUS: 'COM_HEADER_STATUS',
  COM_LOADING_STATUS: 'COM_LOADING_STATUS',
  // user
  SET_USER_INFO: 'SET_USER_INFO',
  SET_LOGIN_INFO: 'SET_LOGIN_INFO',
  GET_USER_DATA: 'GET_USER_DATA',
  // topics
  GET_TOPICS_DETAIL: 'GET_TOPICS_DETAIL',
  // list
  GET_TOPICS_LIST: 'GET_TOPICS_LIST',
  GET_SEARCH_KEY: 'GET_SEARCH_KEY',
  GET_SCROLL_STATUS: 'GET_SCROLL_STATUS',
  GET_PAGE_NUM: 'GET_PAGE_NUM',
  // message
  GET_MSG_LIST: 'GET_MSG_LIST'
}
